version: "3.8"
services:
  web:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    # The new volumes key mounts the project directory (current directory)
    # on the host to /code inside the container, allowing you to modify the code on the fly
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"